# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: SASjs Core Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: SAS Packages Release
        run: |
          npx @sasjs/cli compile job -s sasjs/utils/create_sas_package.sas -o sasjsbuild
          # this part depends on https://github.com/sasjs/server/issues/307
          sasjs run sasjsbuild/jobs/utils/create_sas_package.sas -t sas9
